# BEGIN_KITTY_THEME
# Tango Dark
include current-theme.conf
# END_KITTY_THEME


# BEGIN_KITTY_FONTS
font_family      family="JetBrainsMonoNL Nerd Font Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS


# Custom settings

## Window
remember_window_size no
remember_window_position no
window_margin_width 2
window_padding_width 2

## Tab bar
tab_bar_margin_height 2.0 2.0

## Misc
enabled_layouts splits
copy_on_select yes
scrollback_lines 10000

## OS specific settings
include ${KITTY_OS}.conf

