# BEGIN_KITTY_THEME
# Tango Dark
include current-theme.conf
# END_KITTY_THEME


# BEGIN_KITTY_FONTS
font_family      family=MonoLisaCode style=Light variable_name=MonoLisaCodeRegular features='-calt -liga -dlig +ss10 +ss11'
bold_font        family=MonoLisaCode style=Medium variable_name=MonoLisaCodeRegular features='-calt -liga -dlig +ss10 +ss11'
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS


# Custom settings

## Font
### Customized font settings
font_size 13.0
modify_font underline_position 4
### Nerd Font glyphs
include nerd-font.conf

## Shotcuts
# # HACK: Map Ctrl+-/_ to Ctrl+i/o for muscle memory from VSCode
# map ctrl+- send_key ctrl+i
# map ctrl+_ send_key ctrl+o

## Window
remember_window_size no
remember_window_position no
initial_window_width 800
initial_window_height 600
window_padding_width 2

# ## Tab bar
# tab_bar_margin_height 2.0 2.0
# tab_bar_style powerline
# tab_powerline_style angled

## Misc
enabled_layouts splits
copy_on_select yes
scrollback_lines 10000

## OS specific settings
include ${KITTY_OS}.conf

