# BEGIN_KITTY_THEME
# Tango Dark
include current-theme.conf
# END_KITTY_THEME


# BEGIN_KITTY_FONTS
font_family      family="JetBrainsMonoNL Nerd Font Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS


# Custom settings

## Shotcuts
# # HACK: Map Ctrl+-/_ to Ctrl+i/o for muscle memory from VSCode
# map ctrl+- send_key ctrl+i
# map ctrl+_ send_key ctrl+o

## Window
remember_window_size no
remember_window_position no

# ## Tab bar
# tab_bar_margin_height 2.0 2.0
# tab_bar_style powerline
# tab_powerline_style angled

## Misc
enabled_layouts splits
copy_on_select yes
scrollback_lines 10000

## OS specific settings
include ${KITTY_OS}.conf

