# macOS specific settings

## Simplified Chinese glyphs
symbol_map U+2E80-U+9FFF,U+F900-U+FAFF,U+FF00-U+FFEF "PingFang SC"

## Shortcuts
kitty_mod cmd+shift
map kitty_mod+. next_tab
map kitty_mod+, previous_tab
map kitty_mod+t launch --type=tab --cwd=current
map kitty_mod+enter launch --location=split --cwd=current
map kitty_mod+\ launch --location=vsplit --cwd=current
map kitty_mod+minus launch --location=hsplit --cwd=currentt
map kitty_mod+h neighboring_window left
map kitty_mod+l neighboring_window right
map kitty_mod+j neighboring_window down
map kitty_mod+k neighboring_window up
map kitty_mod+s show_scrollback
map kitty_mod+r start_resizing_window
map kitty_mod+w select_tab
## Window Management (muscle memory from macOS)
map cmd+1 goto_tab 1
map cmd+2 goto_tab 2
map cmd+3 goto_tab 3
map cmd+4 goto_tab 4
map cmd+5 goto_tab 5
map cmd+6 goto_tab 6
map cmd+7 goto_tab 7
map cmd+8 goto_tab 8
map cmd+9 goto_tab 9

## Misc
macos_option_as_alt both
macos_quit_when_last_window_closed yes
