# Set default terminal to tmux-256color
# Force to use user's terminfo
set-env -g TERMINFO $HOME/.terminfo
# Automatically download and install terminfo
if-shell 'test -z "$(find $HOME/.terminfo -name "tmux-256color" -type f 2>/dev/null)" && test -f "$HOME/.tmux/setup_terminfo.sh"' \
	"run-shell 'bash $HOME/.tmux/setup_terminfo.sh'"
set -g default-terminal "tmux-256color"
set -as terminal-features ",*:Tc"

# Undercurl
set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'                                                        # undercurl support
set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m' # underscore colours - needs tmux-3.0

# Enable mouse mode
set -g mouse on

# Allow access to the system clipboard
set -g set-clipboard on

# Start window number with 1
set -g base-index 1

# Renumber window on window close
set -g renumber-windows on

# Rebind prefix to Ctrl+a
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# Enable vi mode
set -g mode-keys vi
set -g status-keys vi

# Bind enter to start copy mode
bind Enter copy-mode

# Split panes with | and -
bind | split-window -h
bind - split-window -v

# Move between panes with hjkl
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Resize panes with Shift + hjkl
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# Create vertical layout with with V
if-shell "test -f $HOME/.tmux/layouts/vertical.sh" \
	"bind V run-shell 'bash $HOME/.tmux/layouts/vertical.sh'"

# Create horizontal layout with with O
if-shell "test -f $HOME/.tmux/layouts/horizontal.sh" \
	"bind O run-shell 'bash $HOME/.tmux/layouts/horizontal.sh'"

# Clear all panes with R
bind R kill-pane -a

# Load custom theme
# if-shell "test -f $HOME/.tmux/themes/kanagawa_dragon.sh" \
# 	"run-shell 'bash $HOME/.tmux/themes/kanagawa_dragon.sh'"
# if-shell "test -f $HOME/.tmux/themes/moonfly.sh" \
# 	"run-shell 'bash $HOME/.tmux/themes/moonfly.sh'"
if-shell "test -f $HOME/.tmux/themes/kanagawa_wave.sh" \
	"run-shell 'bash $HOME/.tmux/themes/kanagawa_wave.sh'"
