onboarding = false

[theme]
name = "catppuccin"
auto_switch = false

# [theme.custom]
# accent = "white"

[update]
# Managed with mise
version_check = false

[keys]
prefix = "ctrl+space"
# Some muscle memories
detach = ["prefix+q", "prefix+d"]
copy_mode = ["prefix+[", "prefix+enter"]
split_vertical = ["prefix+v", "prefix+|"]

[ui]
prompt_new_tab_name = false

[ui.sound]
enabled = false

[ui.toast]
delivery = "terminal"

[ui.toast.clipboard]
enabled = true
