onboarding = false

[theme]
name = "terminal"
auto_switch = false

# [theme.custom]
# # FIX: Make active tab text easy to read
# panel_bg = "black"

[keys]
prefix = "ctrl+space"
# Some muscle memories
detach = ["prefix+q", "prefix+d"]
copy_mode = ["prefix+[", "prefix+enter"]
split_vertical = ["prefix+v", "prefix+|"]

[ui.sound]
enabled = false

[ui.toast]
delivery = "terminal"

[ui.toast.clipboard]
enabled = true
