[tools]
age = "latest"
bat = "latest"
chezmoi = "latest"
delta = "latest"
difftastic = { version = "latest", exe = "difft" }
fd = "latest"
fzf = "latest"
"github:gokcehan/lf" = "latest"
"github:zyedidia/micro" = "latest"
lazygit = "latest"
neovim = "latest"
node = "lts"
"npm:czg" = "latest"
pipx = "latest"
python = "latest"
ripgrep = "latest"
zoxide = "latest"

[settings]
disable_backends = ["asdf"]
python.compile = false
