[tools]
age = "latest"
# "aqua:micro-editor/micro" = "latest"
"aqua:gokcehan/lf" = "latest"
bat = "latest"
bun = "latest"
chezmoi = "latest"
delta = "latest"
difftastic = { version = "latest", exe = "difft" }
fd = "latest"
fzf = "latest"
herdr = "latest"
lazygit = "latest"
neovim = "latest"
node = "lts"
"npm:czg" = "latest"
python = "3.13"
ripgrep = "latest"
# ruff = "latest"
# starship = "latest"
# tmux = "3.7b"
# yazi = "latest"
# zellij = "latest"
zoxide = "latest"

[settings]
disable_backends = ["asdf"]
minimum_release_age = "0s"
