[tools]
gh = "latest"
jq = "latest"
"npm:@bitwarden/cli" = "latest"
"npm:prettier" = "latest"
ruff = "latest"
shfmt = "latest"
stylua = "latest"
taplo = "latest"
uv = "latest"
zellij = "0.43.1"

[settings]
python.compile = false
