[tools]
gh = "latest"
jq = "latest"
"npm:@bitwarden/cli" = "latest"
"npm:prettier" = "latest"
# "pipx:ruff" = "latest"
ruff = "latest"
shfmt = "latest"
stylua = "latest"
taplo = "latest"
uv = "latest"
